### ISSUE TITLE
Symfony3 support

### ISSUE THREAD

**Issue by fkrauthan** [datatheke/DatathekePagerBundle#11]
Do you have any plans to upgrade your bundle to symfony3?

**Comment by iamluc** [comment]
`dev-master` should be compatible with twig 2 & symfony 3.
Could you test and confirm it works for you ?

If it does, I will tag a new version.

**Comment by fkrauthan** [comment]
hey I actually found out a lot more dependencies have issues with symfony3 at the moment so I postponed my upgrade planes for now.
